name: upop
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.6.1=h7f98852_0
  - aom=3.4.0=h27087fc_1
  - attr=2.5.1=h166bdaf_0
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38h0a891b7_1004
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.6.15=ha878542_0
  - cairo=1.16.0=ha61ee94_1011
  - cffi=1.15.1=py38h4a40e3a_0
  - charset-normalizer=2.1.0=pyhd8ed1ab_0
  - cryptography=37.0.4=py38h2b5fc30_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - dbus=1.13.6=h5008d03_3
  - expat=2.4.8=h27087fc_0
  - ffmpeg=4.4.2=gpl_h2b602b6_106
  - fftw=3.3.10=nompi_h77c792f_102
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.0=h8e229c2_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freeglut=3.2.2=h9c3ff4c_1
  - freetype=2.10.4=h0708190_1
  - gettext=0.19.8.1=h73d1719_1008
  - giflib=5.2.1=h36c2ea0_2
  - glib=2.72.1=h6239696_0
  - glib-tools=2.72.1=h6239696_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.7.6=hf3e180e_5
  - graphite2=1.3.13=h58526e2_1001
  - gst-plugins-base=1.20.3=hf6a322e_0
  - gstreamer=1.20.3=hd4edc92_0
  - harfbuzz=4.4.1=hf9f4e7c_0
  - hdf5=1.12.1=nompi_h2386368_104
  - icu=70.1=h27087fc_0
  - idna=3.3=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jack=1.9.18=h8c3723f_1002
  - jasper=2.0.33=ha77e612_0
  - jpeg=9e=h166bdaf_2
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.19.3=h3790be6_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libblas=3.9.0=12_linux64_mkl
  - libcap=2.64=ha37c62d_0
  - libcblas=3.9.0=12_linux64_mkl
  - libclang=14.0.6=default_h2e3cab8_0
  - libclang13=14.0.6=default_h3a83d3e_0
  - libcups=2.3.3=hf5a7f15_1
  - libcurl=7.83.1=h7bff187_0
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.12=h166bdaf_0
  - libdrm=2.4.112=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h7f98852_5
  - libflac=1.3.4=h27087fc_0
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libglib=2.72.1=h2d90d5f_0
  - libglu=9.0.0=he1b5a44_1001
  - libgomp=12.1.0=h8d9b700_16
  - libiconv=1.16=h516909a_0
  - libidn2=2.3.3=h166bdaf_0
  - liblapack=3.9.0=12_linux64_mkl
  - liblapacke=3.9.0=12_linux64_mkl
  - libllvm14=14.0.6=he0ac6c6_0
  - libnghttp2=1.47.0=h727a467_0
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopencv=4.6.0=py38hc65905f_1
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.16=h516909a_0
  - libpng=1.6.37=h753d276_3
  - libpq=14.4=hd77ab85_0
  - libprotobuf=3.20.1=h6239696_0
  - libsndfile=1.0.31=h9c3ff4c_1
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtasn1=4.18.0=h166bdaf_1
  - libtiff=4.4.0=hc85c160_1
  - libtool=2.4.6=h9c3ff4c_1008
  - libudev1=249=h166bdaf_4
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.44.2=h166bdaf_0
  - libva=2.15.0=h166bdaf_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp=1.2.3=h522a892_1
  - libwebp-base=1.2.3=h166bdaf_2
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.14=h22db469_3
  - libzlib=1.2.12=h166bdaf_2
  - lz4-c=1.9.3=h9c3ff4c_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h95df7f1_0
  - mkl_fft=1.3.1=py38h8666266_1
  - mkl_random=1.2.2=py38h1abd341_0
  - mysql-common=8.0.29=haf5c9bc_1
  - mysql-libs=8.0.29=h28c427c_1
  - ncurses=6.3=h27087fc_1
  - nettle=3.8=hc379101_0
  - nspr=4.32=h9c3ff4c_1
  - nss=3.78=h2350873_0
  - numpy=1.22.3=py38he7a7128_0
  - numpy-base=1.22.3=py38hf524024_0
  - openh264=2.2.0=h27087fc_2
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1q=h166bdaf_0
  - p11-kit=0.24.1=hc5aa10d_0
  - pcre=8.45=h9c3ff4c_0
  - pillow=9.2.0=py38h0ee0e06_0
  - pip=22.2=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - portaudio=19.6.0=h57a0ea0_5
  - pthread-stubs=0.4=h36c2ea0_1001
  - pulseaudio=14.0=h7f54b18_8
  - py-opencv=4.6.0=py38h7f3c49e_1
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pysocks=1.7.1=py38h578d9bd_5
  - python=3.8.13=h582c2e5_0_cpython
  - python_abi=3.8=2_cp38
  - pytorch=1.11.0=py3.8_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - qt-main=5.15.4=ha5833f6_2
  - readline=8.1.2=h0f457ee_0
  - requests=2.28.1=pyhd8ed1ab_0
  - ruamel_yaml=0.15.100=py38h27cfd23_0
  - setuptools=63.2.0=py38h578d9bd_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.39.2=h4ff8645_0
  - svt-av1=1.1.0=h27087fc_1
  - tk=8.6.12=h27826a3_0
  - torchaudio=0.11.0=py38_cu113
  - torchvision=0.12.0=py38_cu113
  - typing_extensions=4.3.0=pyha770c72_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - x264=1!161.3030=h7f98852_1
  - x265=3.5=h924138e_3
  - xcb-util=0.4.0=h166bdaf_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h166bdaf_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h166bdaf_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h7f98852_2
  - zlib=1.2.12=h166bdaf_2
  - zstd=1.5.2=h8a70e8d_2
  - pip:
    - addict==2.4.0
    - ansible-cmdb==1.31
    - autocommand==2.2.2
    - boto3==1.26.132
    - botocore==1.29.132
    - certifi==2022.6.15
    - cheroot==10.0.0
    - cherrypy==18.8.0
    - click==8.1.3
    - colorama==0.4.6
    - coloredlogs==15.0.1
    - cycler==0.11.0
    - einops==0.6.1
    - environs==9.5.0
    - fairscale==0.4.4
    - filelock==3.7.1
    - fonttools==4.34.4
    - ftfy==6.1.1
    - fvcore==0.1.5.post20220512
    - gitdb==4.0.10
    - gitpython==3.1.31
    - hostlist==1.4.8
    - huggingface-hub==0.8.1
    - humanfriendly==10.0
    - humanize==4.6.0
    - importlib-metadata==6.7.0
    - importlib-resources==5.12.0
    - inflect==6.0.4
    - iopath==0.1.10
    - jaraco-collections==4.2.0
    - jaraco-context==4.3.0
    - jaraco-functools==3.7.0
    - jaraco-text==3.11.1
    - jmespath==1.0.1
    - joblib==1.1.0
    - jsonxs==0.6
    - kiwisolver==1.4.4
    - line-profiler==4.0.3
    - mako==1.2.4
    - markdown==3.4.3
    - markdown-it-py==3.0.0
    - markupsafe==2.1.3
    - marshmallow==3.19.0
    - matplotlib==3.5.2
    - mdurl==0.1.2
    - mmcv==1.3.8
    - mmengine==0.7.4
    - mmsegmentation==0.14.1
    - model-index==0.1.11
    - more-itertools==9.1.0
    - multiprocessing-logging==0.3.4
    - openmim==0.3.7
    - ordered-set==4.1.0
    - packaging==21.3
    - pandas==2.0.2
    - platformdirs==3.8.0
    - portalocker==2.5.1
    - portend==3.1.0
    - prettytable==3.8.0
    - pycocoevalcap==1.2
    - pycocotools==2.0.4
    - pydantic==1.10.9
    - pygments==2.15.1
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - python-dotenv==1.0.0
    - pytz==2023.3
    - pyyaml==6.0
    - regex==2022.7.25
    - rich==13.4.2
    - s3transfer==0.6.1
    - sacremoses==0.0.53
    - scipy==1.10.1
    - smmap==5.0.0
    - tabulate==0.8.10
    - tempora==5.3.0
    - termcolor==1.1.0
    - thop==0.1.0-2206102148
    - timm==0.4.12
    - tokenizers==0.10.3
    - tomli==2.0.1
    - tqdm==4.64.0
    - transformers==4.15.0
    - typing==3.7.4.3
    - tzdata==2023.3
    - urllib3==1.26.11
    - ushlex==0.99.1
    - wcwidth==0.2.5
    - yacs==0.1.8
    - yapf==0.40.1
    - zc-lockfile==3.0.post1
    - zipp==3.15.0
prefix: /mnt/cache/shidachuan/anaconda3/envs/upop
